export const styles: { [key: string]: React.CSSProperties } = {
  container: {
    position: "relative",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "20px",
    minHeight: "100vh",
    backgroundImage: `url('../../casino.jpg')`,
    backgroundSize: "cover",
    backgroundPosition: "center",
    color: "#ffffff",
    fontFamily: "Arial, sans-serif",
    overflow: "auto",
  },
  connectKitContainer: {
    position: "absolute",
    top: "20px",
    left: "20px",
    zIndex: 1000,
  },
  header: {
    fontSize: "48px",
    fontWeight: "bold",
    marginBottom: "20px",
    textShadow: "2px 2px 5px #000000",
    textAlign: "center",
  },
  balanceContainer: {
    textAlign: "center",
    marginBottom: "20px",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    padding: "15px",
    borderRadius: "10px",
  },
  balanceText: {
    fontSize: "24px",
    margin: "10px 0",
  },
  playerTotalText: {
    fontSize: "20px",
    margin: "5px 0",
  },
  dealerTotalText: {
    fontSize: "20px",
    margin: "5px 0",
    color: "#FFD700",
  },
  betContainer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginTop: "10px",
    flexDirection: "column",
  },
  betLabel: {
    fontSize: "18px",
    marginRight: "10px",
    marginBottom: "8px",
    color: "#AAA",
  },
  inputWrapper: {
    position: "relative",
    display: "flex",
    alignItems: "center",
    border: "1px solid #333",
    borderRadius: "8px",
    padding: "10px 16px",
    backgroundColor: "#000",
  },
  betInput: {
    flex: 1,
    width: "200px",
    fontSize: "36px",
    fontWeight: "bold",
    backgroundColor: "transparent",
    border: "none",
    color: "#fff",
    outline: "none",
    textAlign: "center",
    paddingRight: "40px", // Space for the unit label
  },
  unitLabel: {
    position: "absolute",
    right: "16px",
    fontSize: "24px",
    color: "#FFF",
  },
  subText: {
    fontSize: '14px',
    color: '#888',
    marginTop: '8px',
  },
  // Other styles (startButton, actionButtonsContainer, etc.) go here ...
};
