export const styles: { [key: string]: React.CSSProperties } = {
  container: {
    position: "relative", // To enable absolute positioning of child elements
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "20px",
    minHeight: "100vh",
    backgroundImage: `url('../../casino.jpg')`, // Optional: Add a background image
    backgroundSize: "cover",
    backgroundPosition: "center",
    color: "#ffffff",
    fontFamily: "Arial, sans-serif",
    overflow: "auto", // To handle overflow if content exceeds viewport
  },
  connectKitContainer: {
    position: "absolute",
    top: "20px",
    left: "20px",
    zIndex: 1000, // Ensures the button stays on top
  },
  actionButton: {
    marginTop: "20px",
    padding: "12px 24px",
    fontSize: "18px",
    cursor: "pointer",
    border: "none",
    borderRadius: "8px",
    backgroundColor: "#4CAF50",
    color: "#fff",
    boxShadow: "0 4px 8px rgba(0, 0, 0, 0.2)",
    transition: "background-color 0.3s",
    margin: "10px",
  },

  header: {
    fontSize: "48px",
    fontWeight: "bold",
    marginBottom: "20px",
    textShadow: "2px 2px 5px #000000",
    textAlign: "center",
  },
  balanceContainer: {
    textAlign: "center",
    marginBottom: "20px",
    backgroundColor: "rgba(0, 0, 0, 0.5)", // Semi-transparent background for readability
    padding: "15px",
    borderRadius: "10px",
  },
  balanceText: {
    fontSize: "24px",
    margin: "10px 0",
  },
  playerTotalText: {
    fontSize: "20px",
    margin: "5px 0",
  },
  dealerTotalText: {
    fontSize: "20px",
    margin: "5px 0",
    color: "#FFD700", // Gold color to distinguish dealer's total
  },
  betContainer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginTop: "10px",
  },
  betLabel: {
    fontSize: "18px",
    marginRight: "10px",
  },
  betInput: {
    width: "200px",
    padding: "8px",
    fontSize: "16px",
    borderRadius: "5px",
    border: "2px solid #ffffff",
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    color: "#ffffff",
    textAlign: "center",
    marginTop: "10px",
    marginRight: "10px",
  },
  startButton: {
    marginTop: "20px",
    padding: "12px 24px",
    fontSize: "18px",
    cursor: "pointer",
    border: "none",
    borderRadius: "8px",
    backgroundColor: "#4CAF50",
    color: "#fff",
    boxShadow: "0 4px 8px rgba(0, 0, 0, 0.2)",
    transition: "background-color 0.3s",
  },

  actionButtonsContainer: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    marginTop: "20px",
  },
  hitButton: {
    margin: "0 10px",
    padding: "10px 20px",
    backgroundColor: "#f44336",
    border: "none",
    borderRadius: "8px",
    cursor: "pointer",
    color: "#fff",
    fontSize: "16px",
    boxShadow: "0 4px 8px rgba(0, 0, 0, 0.2)",
    transition: "background-color 0.3s",
  },
  standButton: {
    margin: "0 10px",
    padding: "10px 20px",
    backgroundColor: "#2196F3",
    border: "none",
    borderRadius: "8px",
    cursor: "pointer",
    color: "#fff",
    fontSize: "16px",
    boxShadow: "0 4px 8px rgba(0, 0, 0, 0.2)",
    transition: "background-color 0.3s",
  },
  restartButton: {
    marginTop: "20px",
    padding: "12px 24px",
    fontSize: "18px",
    cursor: "pointer",
    border: "none",
    borderRadius: "8px",
    backgroundColor: "#4CAF50",
    color: "#fff",
    boxShadow: "0 4px 8px rgba(0, 0, 0, 0.2)",
    transition: "background-color 0.3s",
  },
  backButton: {
    marginTop: "10px",
    padding: "12px 24px",
    fontSize: "18px",
    cursor: "pointer",
    border: "none",
    borderRadius: "8px",
    backgroundColor: "#f44336",
    color: "#fff",
    boxShadow: "0 4px 8px rgba(0, 0, 0, 0.2)",
    transition: "background-color 0.3s",
  },
  message: {
    marginTop: "20px",
    fontSize: "22px",
    fontWeight: "bold",
    textShadow: "1px 1px 3px #000000",
    textAlign: "center",
  },
  gameContainer: {
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    marginTop: "20px",
  },
  handsContainer: {
    display: "flex",
    justifyContent: "center",
    gap: "40px",
  },
  nextHandButton: {
    marginTop: "20px",
    fontSize: "24px",
    padding: "10px 20px",
    backgroundColor: "#FFD700",
    border: "none",
    borderRadius: "10px",
    cursor: "pointer",
    fontFamily: "Comic Sans MS, cursive, sans-serif",
    boxShadow: "0 4px 6px rgba(0, 0, 0, 0.1)",
    color: "#fff",
    textShadow: "1px 1px 2px #000",
  },

  changeBetDiv: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    marginTop: "20px",
  },

  betInputLarge: {
    width: "200px",
    padding: "8px",
    fontSize: "16px",
    borderRadius: "5px",
    border: "2px solid #ffffff",
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    color: "#ffffff",
    textAlign: "center",
    marginTop: "10px",
  },
  // ... other styles ...
};
